//eslint-disable-next-line
export default {
  title: 'dark',
  background: '#171717',
  header: '#1E1E1E',
  load: '#FFFFFF',
  color: {
    font: '#FFFFFF',
    primary: '#ED274A',
    secundary: '#FE8671',
    escuro: '#FFFFFF',
    bar: '#1E1E1E',
    outlined: '#853EF3',
    activity: '#B6B6B6',
    price: '#27AE60',
    light: '#FFFFFF',
    blue: '#0092FF',
    red: '#EB5757',
    green: '#7DDEAF',
    text: '#FFFFFF',
    black: '#000000',
    title: '#FFFFFF',
    label: '#BFBFBF',
    off: '#1F1F1F',
    off2: '#2F2F2F',
    background: '#171717',
    border: '#FFFFFF20',
    load: '#FFFFFF',
  },
  size: {
    label: 18,
    title: 24,
    headtitle: 32,
    sublabel: 16,
  },
  font: {
    extrabold: "Products_BoldExtra",
    bold: "Font_Bold",
    bold_italic: "Products_Bold_Italic",
    medium: "Font_Medium",
    medium_italic: "Products_Medium_Italic",
    book: "Font_Book",
    book_italic: "Products_Book_Italic",
  },
  opacity: {
    dez: "#000000",
    oito: "#00000080",
    seis: "#00000060",
    quatro: "#00000040",
    dois: "#00000020",
  },
  padding: {
    top: 60,
  }
}