
const bairros = [ 
    {value: 'Centro', label: 'Centro', }, 
    {value: 'Água Verde', label: 'Água Verde', }, 
    {value: 'Águas Claras', label: 'Águas Claras',  },
    {value: 'Barra do Rio Cerro', label: 'Barra do Rio Cerro', },
    {value: 'Barra do Rio Molha', label: 'Barra do Rio Molha' },
    {value: 'Boa Vista', label: 'Boa Vista', },
    {value: 'Braço do Ribeirão Cavalo', label: 'Braço do Ribeirão Cavalo', },
    {value: 'Centenário', label: 'Centenário',},
    {value: 'Chico de Paulo', label: 'Chico de Paulo',  },
    {value: 'Czerniewicz', label: 'Czerniewicz', },
    {value: 'Estrada Nova', label: 'Estrada Nova', },
    {value: 'Ilha da Figueira', label: 'Ilha da Figueira', },
    {value: 'Jaraguá 84', label: 'Jaraguá 84',  },
    {value: 'Jaraguá 99', label: 'Jaraguá 99',  },
    {value: 'Jaraguá Esquerdo', label: 'Jaraguá Esquerdo',  },
    {value: 'João Pessoa', label: 'João Pessoa', },
    {value: 'Nova Brasília', label: 'Nova Brasília', },
    {value: 'Nereu Ramos', label: 'Nereu Ramos', },
    {value: 'Parque Malwee 10', label: 'Parque Malwee 10' },
    {value: 'Rau', label: 'Rau', },
    {value: 'Rio Cerro I', label: 'Rio Cerro I',  },
    {value: 'Rio Cerro II', label: 'Rio Cerro II' },
    {value: 'Rio da Luz', label: 'Rio da Luz' },
    {value: 'Rio Molha', label: 'Rio Molha',  },
    {value: 'Santa Luzia', label: 'Santa Luzia', },
    {value: 'Santo Antônio 10', label: 'Santo Antônio 10'  },
    {value: 'São Luís', label: 'São Luís', },
    {value: 'Tifa Martins', label: 'Tifa Martins' },
    {value: 'Tifa Monos', label: 'Tifa Monos' },
    {value: 'Três Rios do nsao: 10', label: 'Três Rios do nsao: 10' },
    {value: 'Três Rios do ao: 10', label: 'Três Rios do ao: 10' },
    {value: 'Vieira', label: 'Vieira'},
    {value: 'Vila Baependi 10', label: 'Vila Baependi 10' },
    {value: 'Vila Lalau', label: 'Vila Lalau',  },
    {value: 'Vila Lenzi', label: 'Vila Lenzi',  },
    {value: 'Vila Nova', label: 'Vila Nova',  },
  ]
export default bairros