export const categorias = [
    { value: 'Anal', label: 'Anal' },
    { value: 'Biquíni', label: 'Biquíni' },
    { value: 'Bondage', label: 'Bondage' },
    { value: 'Boquete', label: 'Boquete' },
    { value: 'Bukkake', label: 'Bukkake' },
    { value: 'Camisinha', label: 'Camisinha' },
    { value: 'Chubby', label: 'Chubby' },
    { value: 'Colegial', label: 'Colegial' },
    { value: 'Creampie', label: 'Creampie' },
    { value: 'Dark Skin', label: 'Dark Skin' },
    { value: 'Dormindo', label: 'Dormindo' },
    { value: 'Dupla Penetração', label: 'Dupla Penetração' },
    { value: 'Enfermeira', label: 'Enfermeira' },
    { value: 'Escolar', label: 'Escolar' },
    { value: 'Espanhola', label: 'Espanhola' },
    { value: 'Exibicionismo', label: 'Exibicionismo' },
    { value: 'Fantasia', label: 'Fantasia' },
    { value: 'Footjob', label: 'Footjob' },
    { value: 'Furry', label: 'Furry' },
    { value: 'Futanari', label: 'Futanari' },
    { value: 'Golden Shower', label: 'Golden Shower' },
    { value: 'Grávida', label: 'Grávida' },
    { value: 'Grupal', label: 'Grupal' },
    { value: 'Incesto', label: 'Incesto' },
    { value: 'Kemonomimi', label: 'Kemonomimi' },
    { value: 'Lingerie', label: 'Lingerie' },
    { value: 'Loli', label: 'Loli' },
    { value: 'Lolicon', label: 'Lolicon' },
    { value: 'Maid', label: 'Maid' },
    { value: 'Masturbação', label: 'Masturbação' },
    { value: 'Meia-Calça', label: 'Meia-Calça' },
    { value: 'Milf', label: 'Milf' },
    { value: 'Monstros', label: 'Monstros' },
    { value: 'Nakadashi', label: 'Nakadashi' },
    { value: 'Netorare', label: 'Netorare' },
    { value: 'Óculos', label: 'Óculos' },
    { value: 'Oral', label: 'Oral' },
    { value: 'Paródia', label: 'Paródia' },
    { value: 'Peitinhos', label: 'Peitinhos' },
    { value: 'Peitões', label: 'Peitões' },
    { value: 'Pelos pubianos', label: 'Pelos pubianos' },
    { value: 'Preservativo', label: 'Preservativo' },
    { value: 'Professor', label: 'Professor' },
    { value: 'Professora', label: 'Professora' },
    { value: 'prostituicao', label: 'Prostituição' },
    { value: 'raio-x', label: 'Raio x' },
    { value: 'romance', label: 'Românce' },
    { value: 'sex-toys', label: 'Sex Toys' },
    { value: 'shotacon', label: 'Shotacon' },
    { value: 'sobrenatural', label: 'Sobrenatural' },
    { value: 'succubus', label: 'Succubus' },
    { value: 'suor', label: 'Suor' },
    { value: 'tentaculos', label: 'Tentáculos' },
    { value: 'virgem', label: 'Virgem' }
  ]